### ISSUE TITLE
[ISSUE]: Prometheus IP changes in raspberrypi-docker-monitor stack on restart

### ISSUE THREAD

**Issue by shubham947** [novaspirit/pi-hosted#127]
**Issue**
Prometheus IP changes in _raspberrypi-docker-monitor_ stack on restart, because of which Grafana dashboard shows '**Bad Request**' and no data.

**Comment by rmiddle** [comment]
Did you follow the howto on adding that into the dashboard?  

https://github.com/novaspirit/pi-hosted/blob/master/docs/rpi_docker_monitor.md

**Comment by Griffen8280** [comment]
I've done research on this and found that it is because docker does not always start the container stack in the same order after every reboot.  So on one startup your prometheus instance may get 172.17.0.3 and on next start up because another container was started before it, the prometheus container then gets 172.17.0.4 causing the data source to be no longer viable.  One way to fix it is to reference the container name in the connector address so instead of using http://172.17.0.3:9090 in the data source pane, use http://monitoring-prometheus:9090 and that should work no matter what IP the container gets.  Another way to fix it (and the way I did it) was to redeploy the stack but create a dedicated network for the stack and assign static IP addresses to the containers within.

**Comment by shubham947** [comment]
Thanks
Using http://monitoring-prometheus:9090 instead of http://172.17.0.3:9090 solved the issue.
