### ISSUE TITLE
No Ports Defined in 32bit JSON Template.  On going project.

### ISSUE THREAD

**Issue by tuta23** [novaspirit/pi-hosted#152]
**Question**
There are several containers in the 32b JSON that do not have ports defined. 

**Context**
I have built out an excel review workbook to catch a few port related issues in the JSON files for 32b and 64b

![32b no ports defined](https://user-images.githubusercontent.com/8095757/141377587-be1c5783-501d-4b80-b970-4e684e000fde.JPG)

**Comment by rmiddle** [comment]
Bookstack defines the ports in the stack.
Duck DNS doesn't have an interface to manage.
Homebridge has a Variable to define the port instead of using a standard port.
Nextcloud Port defined in stack
Plex uses host network so they will get a different IP from the DHCP server on ones network.
Watchtower doesn't have a web interface.
WebGrab+Plus doesn't have a web interface
WireGuard Defined in Stack

**Comment by tuta23** [comment]
Thank you -- I'll refer to these notes and not re-submit these as no ports defined.
