### ISSUE TITLE
No Ports Defined in 64bit JSON Template.  On going project.

### ISSUE THREAD

**Issue by tuta23** [novaspirit/pi-hosted#153]
**Question**
There are several containers in the 64b JSON that do not have ports defined. 

**Context**
I have built out an excel review workbook to catch a few port related issues in the JSON files for 32b and 64b

![64b no ports defined](https://user-images.githubusercontent.com/8095757/141377704-63fe8ac3-e38c-4269-9cc4-6d462c4ca042.JPG)

**Comment by rmiddle** [comment]
Bookstack defines the ports in the stack.
Duck DNS doesn't have an interface to manage.
Homebridge has a Variable to define the port instead of using a standard port.
Nextcloud Port defined in stack
Plex uses host network so they will get a different IP from the DHCP server on ones network.
Pritunl Port defined in stack
Watchtower doesn't have a web interface.
WebGrab+Plus doesn't have a web interface
WireGuard Defined in Stack

**Comment by tuta23** [comment]
Thank you!  I'll refer to these notes when I do another review of no defined ports.
