### ISSUE TITLE
[REQUEST] antivirus daemon - clamav

### ISSUE THREAD

**Issue by djayor** [novaspirit/pi-hosted#273]
Will be interesting add a antivirus software on a docker, I didn't test but I believe that can be compatible with Raspberry PI (armv7):
[mkodockx/docker-clamav](https://hub.docker.com/r/mkodockx/docker-clamav)

**Comment by Griffen8280** [comment]
From my reading on the topic this looks like it is meant to be a scanner helper for other servers that you have running.  As such most of the compose files have this as a requirement instead of a standalone install.  This [link](https://github.com/mko-x/docker-clamav/blob/master/docker-compose.yml) describes how to setup a clamav docker instance to scan for Nextcloud on upload.  Of course the container can be deployed in Portainer under the "Containers" tab by clicking "+ Add Container" and inputting `mkodockx/docker-clamav` in the image box, but integrating that later may be difficult without redeploying the containers that you want to integrate with it.
