### ISSUE TITLE
[REQUEST] Graylog

### ISSUE THREAD

**Issue by lars-c** [novaspirit/pi-hosted#340]
Description: Graylog is a centralized logging solution that allows the user to aggregate and search through logs.

https://hub.docker.com/r/graylog/graylog
 	
Only ARM64 supported.

https://docs.graylog.org/docs/docker:  docker-compose example using Docker volumes.

**Comment by Griffen8280** [comment]
Worked on this for the better part of 6-ish hours now.  There are just too many variables within this server system to get everything running properly.  I got it pretty close but it doesn't seem to be truly optimized for a pi and causes my sysload to go nuts when it's trying to run.  I am going to switch gears and look at a possible alternative called syslog-ng.  Looks to do all the same things as graylog but may be slightly better optimized for arm based systems.

**Comment by lars-c** [comment]
For remote log servers I use both rsyslog and syslog-ng (different devices). Graylog is working fine with both – as far as I know. Have a lot of problems with JSON logs, but different kind of issue. A copy of my docker-compose.yml file: https://inetpub.dk/index.php/just-going-through-the-motions/80-graylog-on-raspberry-pi-4 Also some performance data for the Pi as I initial was concerned about load on system. Maybe I have misunderstood your comment?

**Comment by Griffen8280** [comment]
The troubles were on my end.  The way the container for the primary application is setup was causing me fits trying to use it with volume binds instead of letting it spawn it's own volumes for use.  And while it is working on creating those binds and starting up it was causing an enormous load on the system only to crash out later.  I instead went with letting it create persistent volumes to run with and that seemed to do it.  Initial load during startup is a lot (well over 100% on my pi) but once the system is running and settled in its overall load on the system is quite small as the table in the link you have here attests.  I finished creating the template for it last night and created pull request #373.  Once accepted you should see it pop into the list.

**Comment by lars-c** [comment]
Thank you. Took me 3 weeks to get it working :) Had the same problem using host volumes ([host path]:[/container path]) and adding a local 1100 user to [host path]. Never got it working. Never mind – I will look forward to using your Portainer template. Thank you.

**Comment by Griffen8280** [comment]
Pull request was accepted.  It is in the template and should be ready to roll for you.

**Comment by Griffen8280** [comment]
If you pull it successfully and get it going feel free to close this request.

**Comment by lars-c** [comment]
Just tested and everything is working fine. Some great work. First time I installed Graylog it took me 3 weeks – this deployment took 10 minutes. Very Nice. Thank you.
