### ISSUE TITLE
Docker monitor docker related graphs wont work?

### ISSUE THREAD

**Issue by kegma1** [novaspirit/pi-hosted#343]
**Question**
What have i done wrong? none of docker related graphs work. i followed this guide https://youtu.be/IoD3vFuep64.
**Context**
![image](https://user-images.githubusercontent.com/61615726/174860622-4c6352fd-e97a-4f98-9b75-81161dbb5c1b.png)

**Comment by reikolydia** [comment]
Seeing the same issue too, on fresh install

**Comment by reikolydia** [comment]
Turns out, i didnt fully follow the instructions in:
https://github.com/novaspirit/pi-hosted/blob/master/docs/rpi_docker_monitor.md

especially in the Pre-Installation Steps sections.
tldr: ( for Rpios 64 bullseye )
1. `sudo nano /boot/cmdline.txt`
2. `systemd.unified_cgroup_hierarchy=0 cgroup_enable=memory cgroup_memory=1`
3. `sudo reboot`

**Comment by kegma1** [comment]
Was just about to post the same thing xD
